### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by luiztauffer**
WIP

### CODE REVIEW

**Comment by bendichter** [comment]
@luiztauffer what do we need to take this from draft status to pr status?

**Comment by luiztauffer** [comment]
@bendichter 
This currently has basic presentation, installation and usage material, plus a couple of gallery examples and the current API auto-doc. There is a lot of work still to be done here:
- Other usage modes (Voila+Panel, Qt GUI, etc…), which we could include with their related PRs
- More gallery examples, organized by modality
- Improve docstring documentation of existing widgets, we can also include this as we go about refactoring some of them
- Build and publish with actions

But perhaps it would be useful to have this basic docs already merged, so it is easier to contribute to it?

**Comment by bendichter** [comment]
@CodyCBakerPhD can you configure this with readthedocs so we can see the docs compiled in the PR?

**Comment by CodyCBakerPhD** [comment]
Likely needs https://github.com/NeurodataWithoutBorders/nwbwidgets/pull/228

**Comment by CodyCBakerPhD** [comment]
Looks like I need repo permissions, or one of y'all needs to do it

image

**Comment by luiztauffer** [comment]
maybe @bendichter has permission to change that?

**Comment by bendichter** [comment]
@CodyCBakerPhD you now have admin permissions on this repo

**Comment by CodyCBakerPhD** [comment]
Attempting a re-trigger

**Comment by CodyCBakerPhD** [comment]
OK, should be working now

**Comment by CodyCBakerPhD** [comment]
(at least up to encountering build errors)

**Comment by bendichter** [comment]
@luiztauffer can you please look into what is causing the build error?

**Comment by bendichter** [comment]
@luiz looks like you got it! thanks

**Pull request merged**
