### PR TITLE
fix #298

### LINKED ISSUE #298: [Feature]: Alphabetize by subject ID / filename in Panel file listing
### What would you like to see added to NWB Widgets?

When I want to explore a specific file on DANDI, sometimes I will open up dandihub, launch the Panel, select the dandiset, and select the file. This is difficult because the file listing is not in any understandable order:
Screenshot 2023-06-26 at 4 43 35 PM

It would be nice to have the listed files be in order of subject ID and then file name, just like the dandi website. 

I could write code / adapt existing streaming python code to open the file, but sometimes it is just nicer to use a UI.

(And as discussed with @bendichter earlier, this issue would also be solved by being able to select a file in the dandi files explorer and clicking a button "Open in NWB Widgets", but that is a larger issue)

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbwidgets/blob/master/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/NeurodataWithoutBorders/nwbwidgets/issues)?

### PR DESCRIPTION
**Pull request by luiztauffer**
fix #298

Peek 2023-06-30 13-41

### CODE REVIEW

**Comment by luiztauffer** [comment]
@rly @bendichter does it look better now?

**Comment by rly** [comment]
Yes, much better. Thank you!

**Comment by luiztauffer** [comment]
@rly cool, can you approve, so I can merge it?

**Comment by bendichter** [comment]
@luiztauffer I like that you are sorting them, but I don't know about how you are changing the asset paths. It may be a bit more readable, but we are losing the identity with the asset path. If we aren't going to keep the asset path, then we might as well render this better. With your proposal, the subject ID is rendered twice for each asset.

**Review by bendichter — APPROVED** [review]

**Comment by rly** [comment]
Thanks for the fix!

**Pull request merged**
